# Generated by Django 4.0.5 on 2022-07-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('room_type', models.CharField(db_column='room_type', max_length=200)),
                ('price', models.FloatField(db_column='price')),
                ('summary', models.CharField(db_column='summary', max_length=200)),
            ],
            options={
                'db_table': 'listingsAndReviews',
                'managed': False,
            },
        ),
    ]
