# Generated by Django 4.0.5 on 2022-08-02 08:58

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api3UseHotelId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.PositiveIntegerField()),
                ('image_details', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='DestIdChecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destIdFromIndex', models.CharField(db_column='uid', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HotelSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinationorhotel', models.CharField(blank=True, default='-', max_length=300)),
                ('uid', models.CharField(blank=True, max_length=250)),
                ('calendarCheckin', models.DateField(blank=True)),
                ('calendarCheckout', models.DateField(blank=True)),
                ('roomsnumber', models.PositiveIntegerField(blank=True)),
                ('adultsnumber', models.PositiveIntegerField(blank=True)),
                ('childrennumber', models.PositiveIntegerField(blank=True)),
            ],
        ),
    ]
