# Generated by Django 4.0.5 on 2022-07-15 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinationcat',
            options={},
        ),
    ]
