# Generated by Django 4.0.5 on 2022-07-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_destinationcat_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='destinationcat',
            table=None,
        ),
    ]
